EXEC=pi

FC=nvfortran

FOPT=-O2 -mp -acc -ta=tesla:cc60,cc70,time,multicore -Minfo=accel
FHOST=-O2 -mp -acc -ta=tesla:cc60,cc70,time,host -Minfo=accel

default: $(EXEC) pi_big pi_host

$(EXEC): pi.f90 Makefile.myriad Makefile
	$(FC) $(FOPT) -o $(EXEC) pi.f90

pi_big: pi_big.f90 Makefile.myriad Makefile
	$(FC) $(FOPT) -o pi_big pi_big.f90

pi_host: pi_big.f90 Makefile.myriad Makefile
	$(FC) $(FHOST) -o pi_host pi.f90

.PHONY: default
