sbcl:
	PI_ARG=$(PI_ARG) make -f Makefile.sbcl run

ecl:
	PI_ARG=$(PI_ARG) make -f Makefile.ecl run

clisp:
	PI_ARG=$(PI_ARG) make -f Makefile.clisp run

gcl:
	PI_ARG=$(PI_ARG) make -f Makefile.gcl run

clean:
	rm -f pi.fas pi.lib pi.o
