#!/usr/bin/env perl

#use strict;
use warnings;
use Time::HiRes qw( clock );

$num_steps = 1000*1000*10;

if (scalar @ARGV > 0) {
  $num_steps = $ARGV[0];
}

print "Calculating PI with:\n  $num_steps slices\n  1 process\n";

$total_sum = 0;
$step = 1.0 / $num_steps;

$start = clock();

for ($i = 0; $i < $num_steps; $i++) {
  $x = ($i - 0.5) * $step;
  $total_sum += 4.0 / (1.0 + ($x * $x));
}

$pi = $total_sum * $step;

$stop = clock();

printf "Obtained value of PI: %.16g\n" .
       "Time taken: %.16g seconds\n", $pi, $stop - $start;

